# How to Run
#
# ansible-playbook -i hosts.development -k ansible-ibm-websphere/playbooks/was-server-start.yml
#
---
- name:                     "Add Configure LDAP Repository"
  hosts:                    dmgr
  become:                   true
  vars:
    __profile_name:         "{{ profile_name | default('Dmgr01') }}"
    __was_install_location: "{{ was_install_location  | default('/opt/IBM/WebSphere/AppServer') }}"
    __was_nodename:         "{{ was_nodename }}"
    __was_username:         "{{ was_username }}"
    __was_password:         "{{ was_password }}"
    __now:                  "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
    __bin_dir:              "{{ __was_install_location }}/profiles/{{ __profile_name }}/bin"
    __rsp_file:             "{{ __bin_dir }}/was_config_ldap.py"
    __tpl_file:             "was_config_ldap.py.j2"
  tasks:
    - name:                 "Verifiy if Profile already exists"
      stat:
        path:               "{{ __was_install_location }}/profiles/{{ __profile_name }}"
      register:             profile_already_exists

    - name:                 "Generate Response file"
      template:
        src:                "{{ __tpl_file }}"
        dest:               "{{ __rsp_file }}"
      when:                 profile_already_exists.stat.exists == true

    - name:                 "Configure LDAP"
      command:
        chdir={{ __bin_dir }}
        {{ __bin_dir }}/wsadmin.sh -lang jython -port 8879 -username {{ __was_username }} -password {{ __was_password }} -f {{ __rsp_file }}
      register:             cout
      changed_when:         cout.rc == 0
      #changed_when:         ( cout.stdout.find('INSTCONFSUCCESS') != -1)
      when:                 profile_already_exists.stat.exists == true
