# How to Run
#
# ansible-playbooks -i hosts.development -k ansible-ibm-websphere/playbooks/was-profile-cleanup-temps.yml
#
---
- name:                      Cleanup and Truncate files on Log directory
  hosts:                     dmgr, was-servers
  serial:                    1  # run sequentially
  become:                    true
  vars:
    __profile_name:          "{{ profile_name | default('AppSrv01') }}"
    #__was_install_location: "{{ was_install_location  | default('/opt/IBM/WebSphere/AppServer') }}"
    __was_install_location:  "/opt/IBM/WebSphere/AppServer"
  tasks:
    - name:                  "Verify if Java is Running"
      command:               "ps aux"
      register:              java_is_running

    - name:                  "Cleanup temp directories"
      file:
        path:                "{{ __was_install_location }}/profiles/{{ __profile_name }}/{{ item }}"
        state:               absent
      with_items:
        - temp
        - wstemp
        - config/temp
        - tranlog
        - logs
      when:                  (java_is_running.stdout.find(__was_install_location) == -1)
