# Backup WAS before Fix
#
# How to run:
#  ansible-playbook -i hosts.connections -u <USER> -k ansible-ibm-websphere/playbooks/was-backup-dir-pre-fixes.yml
---
- name:              Backup WebSphere DMGR and Nodes pre Fixes
  hosts:             dmgr, was-servers
  become:            true
  vars:
    __ibm_dir:       "{{ ibm_dir | default('/opt/IBM') }}"
    __bkp_dir:       "{{ bkp_dir | default('/opt/IBM/Backup') }}"
    __now_tmp:       "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
    __now:           "{{ __now_tmp }}"

  tasks:

    - name:          Cleanup Backup directory
      file:          path={{ __bkp_dir }} state=absent
      ignore_errors: true

    - name:          Create Backup directory
      file:          path={{item}} state=directory mode=0755
      with_items:
        - "{{ __bkp_dir }}"
        - "{{ __bkp_dir }}/InstallationManager"
        - "{{ __bkp_dir }}/IMShared"
        - "{{ __bkp_dir }}/WebSphere"

    - name:          Create Backup Connections directory
      file:          path={{item}} state=directory mode=0755
      with_items:
        - "{{ __bkp_dir }}/Connections"
      ignore_errors: true

    - name:          Backup Directories
      command:       cp -R {{item}} {{ __bkp_dir }}/
      register:      cout
      with_items:
      - "{{ __ibm_dir }}/InstallationManager"
      - "{{ __ibm_dir }}/IMShared"
      - "{{ __ibm_dir }}/WebSphere"

    - name:          Backup Connections Directories
      command:       cp -R {{item}} {{ __bkp_dir }}/
      register:      cout
      with_items:
      - "{{ __ibm_dir }}/Connections"
      ignore_errors: true

    - name:          Backup Files
      command:       cp {{item}} {{item}}_{{ __now }}
      with_items:
      - /var/ibm/InstallationManager/installed.xml
      - /var/ibm/InstallationManager/installRegistry.xml
      - /var/ibm/InstallationManager/.settings/com.ibm.cic.agent.core.prefs
      register:      cout

    - name:          Disable Repository on Installation Manager
      replace:
        path:        /var/ibm/InstallationManager/.settings/com.ibm.cic.agent.core.prefs
        regexp:      '(\s*)RepositoryIsOpen=true(\s*)'
        replace:     '\1RepositoryIsOpen=false\2'
        backup:      yes
      ignore_errors: true
